#!/usr/bin/env python3
"""
fix_missing_columns.py — Add rank and chkpt_id to ED result CSVs
that were generated by the inline pipeline (post-5a5961d) which
dropped these columns.

For per-model files: rank = row index within file, chkpt_id = rank // batch_size.
For combined files: rank and chkpt_id are computed per model×prompt_set group
to preserve the semantics of "generation order within a run".

Usage:
    python fix_missing_columns.py --batch-size 20
"""
import argparse, glob, os
import pandas as pd


def fix_file(path, batch_size, logger=print):
    df = pd.read_csv(path)

    if 'rank' in df.columns and 'chkpt_id' in df.columns:
        # Check if they're actually populated
        if df['rank'].notna().all() and df['chkpt_id'].notna().all():
            logger(f"  SKIP {path} — already has rank and chkpt_id")
            return False

    is_combined = df['model'].nunique() > 1 if 'model' in df.columns else False

    if is_combined:
        # For combined files, assign rank per model group
        # (each model was a separate run)
        df['rank'] = df.groupby('model').cumcount()
        df['chkpt_id'] = df['rank'] // batch_size
    else:
        df['rank'] = range(len(df))
        df['chkpt_id'] = df['rank'] // batch_size

    df.to_csv(path, index=False)
    logger(f"  FIXED {path} — {len(df)} rows, "
           f"rank 0..{df['rank'].max()}, "
           f"chkpt_id 0..{df['chkpt_id'].max()}")
    return True


def main():
    ap = argparse.ArgumentParser(
        description="Add rank and chkpt_id to ED result CSVs"
    )
    ap.add_argument(
        "--batch-size", type=int, default=20,
        help="Synthetic chkpt_id grouping size (default: 20, matching save_interval)"
    )
    ap.add_argument(
        "--pattern", default="results/ed_*_20260304_*.csv",
        help="Glob pattern for files to fix"
    )
    ap.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be fixed without modifying files"
    )
    args = ap.parse_args()

    files = sorted(glob.glob(args.pattern))
    if not files:
        print(f"No files matching {args.pattern}")
        return

    print(f"Found {len(files)} file(s)")
    for f in files:
        if args.dry_run:
            df = pd.read_csv(f, nrows=1)
            has = 'rank' in df.columns and 'chkpt_id' in df.columns
            print(f"  {'OK' if has else 'NEEDS FIX'} {f}")
        else:
            fix_file(f, args.batch_size)


if __name__ == "__main__":
    main()
